spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: ${redis-database}
    port: ${redis-port}
    host: ${redis-host}
    password: ${redis-password}
management:
  endpoints:
    web:
      exposure:
        include: "*"