spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${ip-authorizer}:${port-authorizer}/rsa/publicKey # 配置RSA的公钥访问地址
  redis:
    database: ${redis-database}
    port: ${redis-port}
    host: ${redis-host}
    password: ${redis-password}
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/goc_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      filters: stat
      initial-size: 5
      max-wait: 6000
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 100
      validation-query: "select 1"
      validation-query-timeout: 6000
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/authorizer/oauth/token"
      - "/authorizer/rsa/publicKey"