spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${ip-authorizer}:${port-authorizer}/rsa/publicKey # 配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/authorizer/oauth/token"
      - "/authorizer/rsa/publicKey"